### PR TITLE
function to query postal code shapes

### PR DESCRIPTION
**Pull request by derhuerst**
thought about renaming `postalCodeShapes` -> `shapes`.

### CODE REVIEW

**Comment by derhuerst** [comment]
bump. (:

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
Would you mind releasing `0.1.0`? Right now, I'd have to rely on the git repo as a dependency, but this is very shaky without tags or branches.

**Comment by juliuste** [comment]
Done.

**Pull request merged**
